### ISSUE TITLE
Contribute format_vp8 to Asterisk?

### ISSUE THREAD

**Issue by seanbright** [meetecho/asterisk-opus#11]
Hi,

Since you are the original copyright holder of format_vp8.c, could you contribute format_vp8.c directly to the Asterisk project?  Since no transcoding is done, I don't see why there would be a legal issue with including it directly with the main distribution.

Regards,
Sean

**Comment by seanbright** [comment]
The version of format_vp8.c in my fork - https://github.com/seanbright/asterisk-opus/blob/master/formats/format_vp8.c - will work with Asterisk 13.  I have a contributor licensing agreement with the Asterisk project, so I can disclaim as necessary.

**Comment by lminiero** [comment]
Hi Sean,

actually I thought that the passthrough stuff for VP8 had already been integrated when we worked on the Opus passthrough patch for Asterisk 12 at the time. No problem at all contributing the code to the main codebase. I have a contributor licensing agreement too, if needed, so any approach you think is the best works for me.

BTW, thanks for keeping this work up-do-date! With so many versions of Asterisk coming out regularly, it's quite hard to make sure they all work fine with these changes...

**Comment by seanbright** [comment]
The pass-through is already there but format_vp8 (reading the file from disk and sending it to the UAC) is not.

Because you are the original copyright holder of format_vp8.c, it would be ideal if you would contribute it to the project.  I can create an issue in JIRA and assign to you if you wish?  What's your JIRA username?

**Comment by seanbright** [comment]
Actually, I am not sure the best way to go about this.  Let me do some research on my side.  Will let you know ASAP.

**Comment by lminiero** [comment]
Ah ok, got it. That format is actually mostly a placeholder. It will indeed save raw VP8 frames, but you won't be able to make use of them, as raw VP8 frames cannot be used without a container that provides some metadata (e.g., webm), not even for replaying, so I'm not sure what use there may be for it in its current stage.

Anyway, feel free to open the JIRA issue and contribute the patch: I'll chime in to confirm it's ok for us to contribute it.

**Comment by seanbright** [comment]
Ahhh.  Well then it might not be worth it.  I'll table this for now.  Thanks!
