### ISSUE TITLE
Strange behavior when calling Asterisk

### ISSUE THREAD

**Issue by nicobouliane** [meetecho/asterisk-opus#15]
Hello,
So when I call from a softphone (gsm) to another softphone (opus), the transcoding path works perfectly.

When I call *99 from a softphone (opus) to take my voicemail, the sound is very choppy.

Any Idea what could cause this ?

**Comment by Dimitripietro** [comment]
Nicolas, using Bria (opus codec) and Asterisk 11.20 I don't have this issue

**Comment by nicobouliane** [comment]
We finally found the problem... the timing module wasn't loaded !
